[package]
name = "rmqqt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.36", features = ["derive"] }
futures-util = "0.3.31"
paho-mqtt = "0.13.2"
tokio = { version = "1.44.2", features = ["rt", "tokio-macros", "process", "full"] }
